version: '3'
services:
#mssql docker
  visitbosnia-sql:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=QWElkj132!
      - MSSQL_PID=Developer    
    ports:
      - 1401:1433
    expose:
        - 1433
    networks:
      - VisitBosnianet

  visitbosnia-api:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ConnectionStrings:DefaultConnection=Server=visitbosnia-sql,1433;Database=180065_180066;User=sa;Password=QWElkj132!;ConnectRetryCount=0
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5223:5223
    networks:
      - VisitBosnianet     
    links:
      - visitbosnia-sql
    depends_on:
      - visitbosnia-sql
      
networks:
  VisitBosnianet:
    driver: bridge 